// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VerafinViewer.Entities;

public partial class FileCount
{
    public long Id { get; set; }

    public string PickupLocation { get; set; }

    public int PickupLocationCount { get; set; }

    public int CopiedCount { get; set; }

    public DateTime DateInserted { get; set; }
}