// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VerafinViewer.Entities;

public partial class Logs
{
    public long Id { get; set; }

    public DateTime DateInserted { get; set; }

    public string ProcessMessage { get; set; }

    public string MessageType { get; set; }
}