// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VerafinFileMover.Entities;

public partial class DirectoryInfo
{
    public int Id { get; set; }

    public string Pickup { get; set; }

    public string Dropoff { get; set; }

    public int FrequencyMinutes { get; set; }

    public DateTime LastRunTime { get; set; }

    public bool Active { get; set; }

    public string DateFormat { get; set; }

    public string FriendlyLocationName { get; set; }

    public string NewDateFormat { get; set; }

    public string NamingScheme { get; set; }
}