// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VerafinFileMover.Entities;

public partial class FilesProcessed
{
    public long Id { get; set; }

    public int DirectoryInfoId { get; set; }

    public string Filename { get; set; }

    public DateTime DateCopied { get; set; }

    public string NewFilename { get; set; }
}