// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace VerafinFileMover.Entities;

public partial class VerafinFileMoverContext : DbContext
{
    public VerafinFileMoverContext(DbContextOptions<VerafinFileMoverContext> options)
        : base(options)
    {
    }

    public virtual DbSet<DirectoryInfo> DirectoryInfo { get; set; }

    public virtual DbSet<FileCount> FileCount { get; set; }

    public virtual DbSet<FilesProcessed> FilesProcessed { get; set; }

    public virtual DbSet<Logs> Logs { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<DirectoryInfo>(entity =>
        {
            entity.Property(e => e.Active).HasDefaultValue(true, "DF_DirectoryInfo_Active");
            entity.Property(e => e.DateFormat)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Dropoff)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.FriendlyLocationName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.LastRunTime).HasDefaultValueSql("(getdate())", "DF_DirectoryInfo_LastRunTime");
            entity.Property(e => e.NamingScheme)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.NewDateFormat)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Pickup)
                .IsRequired()
                .HasMaxLength(500);
        });

        modelBuilder.Entity<FileCount>(entity =>
        {
            entity.Property(e => e.DateInserted).HasDefaultValueSql("(getdate())", "DF_FileCount_DateInserted");
            entity.Property(e => e.PickupLocation)
                .IsRequired()
                .HasMaxLength(500);
        });

        modelBuilder.Entity<FilesProcessed>(entity =>
        {
            entity.Property(e => e.DateCopied).HasDefaultValueSql("(getdate())", "DF_FilesProcessed_DateCopied");
            entity.Property(e => e.Filename).IsRequired();
        });

        modelBuilder.Entity<Logs>(entity =>
        {
            entity.Property(e => e.DateInserted).HasDefaultValueSql("(getdate())", "DF_Logs_DateInserted");
            entity.Property(e => e.MessageType)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ProcessMessage).IsRequired();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}